spring:
  application:
    name: employee-management-api
  datasource:
    url: jdbc:postgresql://localhost:5432/ems
    username: ${DB_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true