spring:
  application:
    name: employee-management-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/ems
    username: ${DB_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${NEON_DATABASE_URL}
    username: ${NEON_USERNAME}
    password: ${NEON_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
---
logging:
  file:
    name: logs/employee-api.log
  level:
    root: INFO
    de.fherold: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"